# Generated by Django 5.2 on 2025-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
